apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: storagebs-manager
  name: storagebs-manager
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: storagebs-manager
  template:
    metadata:
      labels:
        app: storagebs-manager
    spec:
      containers:
      - name: storagebs-manager
        image: "{{ .Values.image.storagebs.manager }}:{{ .Values.image.storagebs.managerTag }}"
        imagePullPolicy: Always
        securityContext:
          privileged: true
        command:
        - longhorn-manager
        - -d
        - daemon
        - --engine-image
        - "{{ .Values.image.storagebs.engine }}:{{ .Values.image.storagebs.engineTag }}"
        - --instance-manager-image
        - "{{ .Values.image.storagebs.instanceManager }}:{{ .Values.image.storagebs.instanceManagerTag }}"
        - --manager-image
        - "{{ .Values.image.storagebs.manager }}:{{ .Values.image.storagebs.managerTag }}"
        - --service-account
        - storagebs-service-account
        ports:
        - containerPort: 9500
          name: manager
        volumeMounts:
        - name: dev
          mountPath: /host/dev/
        - name: proc
          mountPath: /host/proc/
        - name: varrun
          mountPath: /var/run/
        - name: cubepaas
          mountPath: /var/lib/cubepaas/bs/
          mountPropagation: Bidirectional
        - name: storagebs-default-setting
          mountPath: /var/lib/cubepaas-setting/
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CUBEPAAS_BACKEND_SVC
          value: storagebs-backend
        - name: DEFAULT_SETTING_PATH
          value: /var/lib/cubepaas-setting/default-setting.yaml
      volumes:
      - name: dev
        hostPath:
          path: /dev/
      - name: proc
        hostPath:
          path: /proc/
      - name: varrun
        hostPath:
          path: /var/run/
      - name: cubepaas
        hostPath:
          path: /var/lib/cubepaas/bs/
      - name: storagebs-default-setting
        configMap:
          name: storagebs-default-setting
      serviceAccountName: storagebs-service-account
  updateStrategy:
    rollingUpdate:
      maxUnavailable: "100%"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: storagebs-manager
  name: storagebs-backend
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.manager.type }}
  sessionAffinity: ClientIP
  selector:
    app: storagebs-manager
  ports:
  - name: manager
    port: 9500
    targetPort: manager
    {{- if .Values.service.manager.nodePort }}
    nodePort: {{ .Values.service.manager.nodePort }}
    {{- end }}
