apiVersion: v1
kind: ConfigMap
metadata:
  name: storagebs-default-setting
  namespace: {{ .Release.Namespace }}
data:
  default-setting.yaml: |-
    backup-target: {{ .Values.defaultSettings.backupTarget }}
    interface-name: {{ .Values.defaultSettings.interfaceName }}
    host-network: {{ .Values.defaultSettings.hostNetwork }}    
    backup-target-credential-secret: {{ .Values.defaultSettings.backupTargetCredentialSecret }}
    create-default-disk-labeled-nodes: {{ .Values.defaultSettings.createDefaultDiskLabeledNodes }}
    default-data-path: {{ .Values.defaultSettings.defaultDataPath }}
    replica-soft-anti-affinity: {{ .Values.defaultSettings.replicaSoftAntiAffinity }}
    storage-over-provisioning-percentage: {{ .Values.defaultSettings.storageOverProvisioningPercentage }}
    storage-minimal-available-percentage: {{ .Values.defaultSettings.storageMinimalAvailablePercentage }}
    upgrade-checker: {{ .Values.defaultSettings.upgradeChecker }}
    default-replica-count: {{ .Values.defaultSettings.defaultReplicaCount }}
    guaranteed-engine-cpu: {{ .Values.defaultSettings.guaranteedEngineCPU }}
    default-longhorn-static-storage-class: {{ .Values.defaultSettings.defaultLonghornStaticStorageClass }}
    backupstore-poll-interval: {{ .Values.defaultSettings.backupstorePollInterval }}
    taint-toleration: {{ .Values.defaultSettings.taintToleration }}
    registry-secret: {{ .Values.defaultSettings.registrySecret }}
