apiVersion: longhorn.io/v1beta1
kind: Setting
metadata:
  labels:
    cubepaas.com/creator: linkcloud
  name: interface-name
  namespace: {{ .Release.Namespace }}
value: {{ .Values.defaultSettings.interfaceName }}