apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: storagebs-manager
  name: storagebs-manager
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: storagebs-manager
  template:
    metadata:
      labels:
        app: storagebs-manager
    spec:
      initContainers:
      - name: install
        image: registry.cn-hangzhou.aliyuncs.com/link-cloud/initcubepaas-bs:v0.5.1
        imagePullPolicy: Always
        command: ["/bin/sh","-c","/home/init.sh && ls /sbin/iscsi*"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: iscsiusr
          mountPath: /sbin/
        - name: etc
          mountPath: /etc/ 
      containers:
      - name: storagebs-manager
        image: "{{ .Values.image.cubepaas.manager }}:{{ .Values.image.cubepaas.managerTag }}"
        imagePullPolicy: Always
        securityContext:
          privileged: true
        command:
        - longhorn-manager
        - -d
        - daemon
        - --engine-image
        - "{{ .Values.image.cubepaas.engine }}:{{ .Values.image.cubepaas.engineTag }}"
        - --manager-image
        - "{{ .Values.image.cubepaas.manager }}:{{ .Values.image.cubepaas.managerTag }}"
        - --service-account
        - storagebs-service-account
        ports:
        - containerPort: 9500
          name: manager
        resources:
          limits:
            cpu: {{ .Values.resources.manager.limits.cpu }}
            memory: {{ .Values.resources.manager.limits.memory }}
          requests:
            cpu: {{ .Values.resources.manager.requests.cpu }}
            memory: {{ .Values.resources.manager.requests.cpu }}
        volumeMounts:
        - name: dev
          mountPath: /host/dev/
        - name: proc
          mountPath: /host/proc/
        - name: varrun
          mountPath: /var/run/
        - name: cubepaas
          mountPath: /var/lib/cubepaas/bs/
          mountPropagation: Bidirectional
        - name: cubepaas-default-setting
          mountPath: /var/lib/bs/setting/
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CUBEPAAS_BACKEND_SVC
          value: storagebs-backend
        - name: DEFAULT_SETTING_PATH
          value: /var/lib/bs/setting/default-setting.yaml
      volumes:
      - name: etc
        hostPath:
          path: /etc/
      - name: iscsiusr
        hostPath:
          path: /sbin/
      - name: dev
        hostPath:
          path: /dev/
      - name: proc
        hostPath:
          path: /proc/
      - name: varrun
        hostPath:
          path: /var/run/
      - name: cubepaas
        hostPath:
          path: /var/lib/cubepaas/bs/
      - name: cubepaas-default-setting
        configMap:
          name: cubepaas-default-setting
      serviceAccountName: storagebs-service-account
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: storagebs-manager
  name: storagebs-backend
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.manager.type }}
  sessionAffinity: ClientIP
  selector:
    app: storagebs-manager
  ports:
  - name: manager
    port: 9500
    targetPort: manager
    {{- if .Values.service.manager.nodePort }}
    nodePort: {{ .Values.service.manager.nodePort }}
    {{- end }}
