apiVersion: longhorn.io/v1beta1
kind: Setting
metadata:
  labels:
    cubepaas.com/creator: linkcloud
  name: default-data-path
  namespace: {{ .Release.Namespace }}
value: {{ .Values.defaultSettings.defaultDataPath }}