apiVersion: longhorn.io/v1beta1
kind: Setting
metadata:
  labels:
    cubepaas.com/creator: linkcloud
  name: default-replica-count
  namespace: {{ .Release.Namespace }}
value: "{{ .Values.defaultSettings.defaultReplicaCount }}"