apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.defaultSettings.backupTargetCredentialSecret }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.awsSecret.accessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsSecret.secretKey | b64enc }}
  AWS_ENDPOINTS: {{ .Values.awsSecret.endPoints | b64enc }}