kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storagebs
  {{- if .Values.persistence.defaultClass }}
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  {{- else }}
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
  {{- end }}
provisioner: driver.cubepaas.com
parameters:
  numberOfReplicas: "{{ .Values.persistence.defaultClassReplicaCount }}"
  staleReplicaTimeout: "30"
  fromBackup: ""
  baseImage: ""
